### ISSUE TITLE
Make this work for non-privileged user

### ISSUE THREAD

**Issue by nickdavis2001** [ministryofjustice/opg-infra-costs#8]
Use accounts in such a way that someone without breakglass access can clone the repo and run this straightaway

**Comment by charlesmmarshall** [comment]
Currently we're having to use the breakglass role as billing role is missing some api permissions on some accounts

this failure is also hidden as the code swallows the error (i think)

**Comment by charlesmmarshall** [comment]
We have the billing role in most places now & the code has been updated so if you cant access an account the account is skipped rather than failing
